In [1]:
import sys
sys.path.append('..')

In [2]:
from Deployment.data_clean import (read_provider_data,
                                    read_ip_data,
                                    read_op_data,
                                    read_beneficiary_data,
                                    aggregate_ip_data,
                                    aggregate_op_data,
                                    aggregate_beneficiary_data,
                                    prepare_model_input)

In [3]:
help(read_provider_data)

Help on function read_provider_data in module Deployment.data_clean:

read_provider_data(path: str, nrows: Optional[int] = None) -> pandas.DataFrame

In [4]:
provider=read_provider_data(path="Prediction_Data/Test_Master_Providers.csv")
provider.head()

INFO:Deployment.data_clean:Reading provider data from: C:\Users\MK PERUMALLA\OneDrive\Desktop\Fraud_Analytics\Prediction_Data\Test_Master_Providers.csv
INFO:Deployment.data_clean:Loaded 1,353 rows × 1 columns.

   Provider
0  PRV51002
1  PRV51006
2  PRV51009
3  PRV51010
4  PRV51018

In [5]:
ip_data=read_ip_data("Prediction_Data/Test_Inpatientdata.csv")
ip_data.head()

INFO:Deployment.data_clean:Reading inpatient data from: C:\Users\MK PERUMALLA\OneDrive\Desktop\Fraud_Analytics\Prediction_Data\Test_Inpatientdata.csv
INFO:Deployment.data_clean:Loaded 9,551 rows × 30 columns.
WARNING:Deployment.data_clean:File 'Prediction_Data/Test_Inpatientdata.csv' is missing expected column(s): ['OP_InscClaimAmtReimbursed', 'OP_DeductibleAmtPaid']
INFO:Deployment.data_clean:Derived 'IP_Number_of_Days_in_Hospital' from 'AdmissionDt' → 'DischargeDt'.
INFO:Deployment.data_clean:Derived 'IP_Claim_Days' from 'ClaimStartDt' → 'ClaimEndDt'.
INFO:Deployment.data_clean:Computed IP_Unique_Disease_Count and IP_Unique_Treatment_Count.
INFO:Deployment.data_clean:Renamed columns: {'ClaimID': 'IP_ClaimID', 'InscClaimAmtReimbursed': 'IP_InscClaimAmtReimbursed', 'DeductibleAmtPaid': 'IP_DeductibleAmtPaid'}
INFO:Deployment.data_clean:Preprocessing complete. Output shape: (9551, 9)

,BeneID,IP_ClaimID,Provider,IP_InscClaimAmtReimbursed,IP_DeductibleAmtPaid,IP_Number_of_Days_in_Hospital,IP_Claim_Days,IP_Unique_Disease_Count,IP_Unique_Treatment_Count
0,BENE11014,CLM67387,PRV57070,9000,1068.0,7,7,10,2
1,BENE11017,CLM31237,PRV54750,14000,1068.0,14,14,9,1
2,BENE11026,CLM78930,PRV53758,2000,1068.0,4,4,9,0
3,BENE11031,CLM56810,PRV55825,16000,1068.0,13,13,10,2
4,BENE11085,CLM34625,PRV52338,19000,1068.0,11,11,8,0

In [6]:
op_data=read_op_data("Prediction_Data/Test_Outpatientdata.csv")
op_data.head()

INFO:Deployment.data_clean:reading Outpatient data from C:\Users\MK PERUMALLA\OneDrive\Desktop\Fraud_Analytics\Prediction_Data\Test_Outpatientdata.csv
INFO:Deployment.data_clean:Loaded 125,841 rows × 27 columns.
WARNING:Deployment.data_clean:File 'Prediction_Data/Test_Outpatientdata.csv' is missing expected column(s): ['OP_InscClaimAmtReimbursed', 'OP_DeductibleAmtPaid']
INFO:Deployment.data_clean:Date columns parsed successfully and derrived new col
INFO:Deployment.data_clean:Computed OP_Unique_Disease_Count and OP_Unique_Treatment_Count.
INFO:Deployment.data_clean:Renamed columns: {'ClaimID': 'OP_ClaimID', 'InscClaimAmtReimbursed': 'OP_InscClaimAmtReimbursed', 'DeductibleAmtPaid': 'OP_DeductibleAmtPaid'}
INFO:Deployment.data_clean:Preprocessing complete. Output shape: (125841, 8)

,BeneID,OP_ClaimID,Provider,OP_InscClaimAmtReimbursed,OP_DeductibleAmtPaid,OP_Claim_Days,OP_Unique_Disease_Count,OP_Unique_Treatment_Count
0,BENE11001,CLM392397,PRV55962,30,0,0,6,0
1,BENE11001,CLM430760,PRV56112,30,0,0,3,0
2,BENE11007,CLM233081,PRV56979,200,0,0,1,0
3,BENE11007,CLM496381,PRV56573,10,0,0,2,0
4,BENE11007,CLM521391,PRV56573,10,0,0,1,0

In [7]:
benf_data=read_beneficiary_data("Prediction_Data/Test_Beneficiarydata.csv")
benf_data.head()

INFO:Deployment.data_clean:Reading beneficiary data from: C:\Users\MK PERUMALLA\OneDrive\Desktop\Fraud_Analytics\Prediction_Data\Test_Beneficiarydata.csv
INFO:Deployment.data_clean:Loaded 63,968 rows × 19 columns.

,BeneID,RenalDiseaseIndicator,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,0,12,12,0,1,0,1,1,0,0,0,1,0,0,36000,3204,60,70
1,BENE11007,0,12,12,0,0,1,1,1,1,0,1,0,0,1,0,0,1490,160
2,BENE11010,0,12,12,1,0,1,0,0,1,0,0,0,1,1,0,0,1170,660
3,BENE11011,0,12,12,1,0,0,1,1,0,0,1,1,0,0,5000,1068,250,320
4,BENE11014,1,12,12,1,0,0,1,0,0,1,0,1,1,1,21260,2136,120,100

In [8]:
ip_final=aggregate_ip_data(ip_data,provider)
ip_final.head()

,Provider,IP_Claim_Count,IP_Benf_Count,Avg_IP_InscClaimAmtReimbursed,Avg_IP_DeductibleAmtPaid,Avg_IP_Number_of_Days_in_Hospital,Avg_IP_Claim_Days,Avg_IP_Unique_Disease_Count,Avg_IP_Unique_Treatment_Count
0,PRV51002,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,PRV51006,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,PRV51009,2,2,7500.000000,1068.0,3.0,3.0,5.0,1.0
3,PRV51010,6,5,9333.333333,1068.0,0.0,0.0,5.0,0.0
4,PRV51018,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
op_final=aggregate_op_data(op_data,provider)
op_final.head()

,Provider,OP_Claim_Count,OP_Benf_Count,Avg_OP_InscClaimAmtReimbursed,Avg_OP_DeductibleAmtPaid,Avg_OP_Claim_Days,Avg_OP_Unique_Disease_Count,Avg_OP_Unique_Treatment_Count
0,PRV51002,205,169,262.390244,1.853659,0.0,1.0,0.0
1,PRV51006,102,81,301.176471,0.000000,0.0,1.0,0.0
2,PRV51009,37,28,330.540541,4.594595,0.0,1.0,0.0
3,PRV51010,32,22,268.125000,0.000000,0.0,1.0,0.0
4,PRV51018,190,146,324.315789,3.526316,0.0,1.0,0.0

In [12]:
benf_final=aggregate_beneficiary_data(benf_data,ip_data,op_data)
benf_final.head()

,Provider,Total_Beneficiaries,RenalDisease_Count,Alzheimer_Count,HeartFailure_Count,KidneyDisease_Count,Cancer_Count,Pulmonary_Count,Depression_Count,Diabetes_Count,IschemicHeart_Count,Osteoporosis_Count,RheumatoidArthritis_Count,Stroke_Count,Avg_PartA_Months,Avg_PartB_Months_Mode,Avg_IP_Reimbursement,Avg_IP_Deductible,Avg_OP_Reimbursement,Avg_OP_Deductible
0,PRV51002,169,24,106,78,115,150,120,97,50,46,120,124,156,12,12,4719.467456,519.692308,2064.852071,594.497041
1,PRV51006,81,10,55,31,45,69,57,46,28,18,60,66,73,12,12,3670.246914,458.962963,2439.259259,671.358025
2,PRV51009,30,4,22,14,20,29,23,18,10,8,19,26,27,12,12,3905.333333,320.400000,2985.333333,729.333333
3,PRV51010,25,3,14,12,16,21,18,14,6,6,17,19,21,12,12,4168.000000,384.480000,2002.000000,632.800000
4,PRV51018,146,28,90,69,78,126,106,81,36,45,100,110,137,12,12,3911.438356,409.643836,2330.821918,689.589041

In [3]:
help(prepare_model_input)

Help on function prepare_model_input in module Deployment.data_clean:

prepare_model_input(provider_path: str, ip_path: str, op_path: str, benf_path: str, output_path: str, nrows: Optional[int] = None) -> pandas.DataFrame
    Prepare the complete model input dataset by reading, preprocessing, aggregating, and merging all data sources.

    Parameters
    ----------
    provider_path : str
        Path to provider data CSV.
    ip_path : str
        Path to inpatient data CSV.
    op_path : str
        Path to outpatient data CSV.
    benf_path : str
        Path to beneficiary data CSV.
    output_path : str
        Path to save the output CSV.
    nrows : int, optional
        Number of rows to read from each file.

    Returns
    -------
    pd.DataFrame
        The final merged dataset.

In [3]:
provider_path="Prediction_Data/Test_Master_Providers.csv"
ip_path="Prediction_Data\Test_Inpatientdata.csv"
op_path="Prediction_Data\Test_Outpatientdata.csv"
benf_path="Prediction_Data\Test_Beneficiarydata.csv"
output_path="Model_Input_Data/prediction_input_data.csv"

final_test_data=prepare_model_input(provider_path=provider_path,ip_path=ip_path,op_path=op_path,benf_path=benf_path,output_path=output_path)
print(f"Dimension {final_test_data.shape}\n Head {final_test_data.head()}")

INFO:Deployment.data_clean:Reading provider data from: C:\Users\MK PERUMALLA\OneDrive\Desktop\Fraud_Analytics\Prediction_Data\Test_Master_Providers.csv
INFO:Deployment.data_clean:Loaded 1,353 rows × 1 columns.
INFO:Deployment.data_clean:Reading inpatient data from: C:\Users\MK PERUMALLA\OneDrive\Desktop\Fraud_Analytics\Prediction_Data\Test_Inpatientdata.csv
INFO:Deployment.data_clean:Loaded 9,551 rows × 30 columns.
WARNING:Deployment.data_clean:File 'Prediction_Data\Test_Inpatientdata.csv' is missing expected column(s): ['OP_InscClaimAmtReimbursed', 'OP_DeductibleAmtPaid']
INFO:Deployment.data_clean:Derived 'IP_Number_of_Days_in_Hospital' from 'AdmissionDt' → 'DischargeDt'.
INFO:Deployment.data_clean:Derived 'IP_Claim_Days' from 'ClaimStartDt' → 'ClaimEndDt'.
INFO:Deployment.data_clean:Computed IP_Unique_Disease_Count and IP_Unique_Treatment_Count.
INFO:Deployment.data_clean:Renamed columns: {'ClaimID': 'IP_ClaimID', 'InscClaimAmtReimbursed': 'IP_InscClaimAmtReimbursed', 'DeductibleAmtPaid': 'IP_DeductibleAmtPaid'}
INFO:Deployment.data_clean:Preprocessing complete. Output shape: (9551, 9)
INFO:Deployment.data_clean:reading Outpatient data from C:\Users\MK PERUMALLA\OneDrive\Desktop\Fraud_Analytics\Prediction_Data\Test_Outpatientdata.csv
INFO:Deployment.data_clean:Loaded 125,841 rows × 27 columns.
WARNING:Deployment.data_clean:File 'Prediction_Data\Test_Outpatientdata.csv' is missing expected column(s): ['OP_InscClaimAmtReimbursed', 'OP_DeductibleAmtPaid']
INFO:Deployment.data_clean:Date columns parsed successfully and derrived new col
INFO:Deployment.data_clean:Computed OP_Unique_Disease_Count and OP_Unique_Treatment_Count.
INFO:Deployment.data_clean:Renamed columns: {'ClaimID': 'OP_ClaimID', 'InscClaimAmtReimbursed': 'OP_InscClaimAmtReimbursed', 'DeductibleAmtPaid': 'OP_DeductibleAmtPaid'}
INFO:Deployment.data_clean:Preprocessing complete. Output shape: (125841, 8)
INFO:Deployment.data_clean:Reading beneficiary data from: C:\Users\MK PERUMALLA\OneDrive\Desktop\Fraud_Analytics\Prediction_Data\Test_Beneficiarydata.csv
INFO:Deployment.data_clean:Loaded 63,968 rows × 19 columns.
INFO:Deployment.data_clean:Saved merged model input data to: C:\Users\MK PERUMALLA\OneDrive\Desktop\Fraud_Analytics\Model_Input_Data\prediction_input_data.csv (shape=(1353, 35))

Dimension (1353, 35)
 Head    Provider  IP_Claim_Count  IP_Benf_Count  Avg_IP_InscClaimAmtReimbursed  \
0  PRV51002               0              0                       0.000000
1  PRV51006               0              0                       0.000000
2  PRV51009               2              2                    7500.000000
3  PRV51010               6              5                    9333.333333
4  PRV51018               0              0                       0.000000

   Avg_IP_DeductibleAmtPaid  Avg_IP_Number_of_Days_in_Hospital  \
0                       0.0                                0.0
1                       0.0                                0.0
2                    1068.0                                3.0
3                    1068.0                                0.0
4                       0.0                                0.0

   Avg_IP_Claim_Days  Avg_IP_Unique_Disease_Count  \
0                0.0                          0.0
1                0.0                          0.0
2                3.0                          5.0
3                0.0                          5.0
4                0.0                          0.0

   Avg_IP_Unique_Treatment_Count  OP_Claim_Count  ...  IschemicHeart_Count  \
0                            0.0             205  ...                   46
1                            0.0             102  ...                   18
2                            1.0              37  ...                    8
3                            0.0              32  ...                    6
4                            0.0             190  ...                   45

   Osteoporosis_Count  RheumatoidArthritis_Count  Stroke_Count  \
0                 120                        124           156
1                  60                         66            73
2                  19                         26            27
3                  17                         19            21
4                 100                        110           137

   Avg_PartA_Months  Avg_PartB_Months_Mode  Avg_IP_Reimbursement  \
0                12                     12           4719.467456
1                12                     12           3670.246914
2                12                     12           3905.333333
3                12                     12           4168.000000
4                12                     12           3911.438356

   Avg_IP_Deductible  Avg_OP_Reimbursement  Avg_OP_Deductible
0         519.692308           2064.852071         594.497041
1         458.962963           2439.259259         671.358025
2         320.400000           2985.333333         729.333333
3         384.480000           2002.000000         632.800000
4         409.643836           2330.821918         689.589041

[5 rows x 35 columns]

In [7]:
final_test_data.to_csv('../Model_Input_Data/prediction_input_data.csv',mode='w')