In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,roc_auc_score,confusion_matrix,classification_report

### Load Model Input Data

In [7]:
df=pd.read_csv("../Model_Input_Data/Model_Input_Data.csv")
print(df.shape)
df.head()

(5410, 36)

,Provider,PotentialFraud,IP_Claim_Count,IP_Benf_Count,Avg_IP_InscClaimAmtReimbursed,Avg_IP_DeductibleAmtPaid,Avg_IP_Number_of_Days_in_Hospital,Avg_IP_Number_of_Days_in_Hospital.1,Avg_IP_Number_of_Days_in_Hospital.2,Avg_IP_Number_of_Days_in_Hospital.3,...,IschemicHeart_Count,Osteoporosis_Count,RheumatoidArthritis_Count,Stroke_Count,Avg_PartA_Months,Avg_PartB_Months_Mode,Avg_IP_Reimbursement,Avg_IP_Deductible,Avg_OP_Reimbursement,Avg_OP_Deductible
0,PRV51001,0,5,5,19400.000000,1068.0,0.0,0.0,6.0,0.0,...,2,18,16,19,12,12,18047.916667,890.000000,2537.500000,474.916667
1,PRV51003,1,62,53,9241.935484,1068.0,3.0,3.0,9.0,1.0,...,18,89,85,108,12,12,6814.017094,822.632479,2490.598291,664.529915
2,PRV51004,0,0,0,0.000000,0.0,0.0,0.0,0.0,0.0,...,40,95,97,122,12,12,4596.739130,454.144928,2095.144928,600.869565
3,PRV51005,1,0,0,0.000000,0.0,0.0,0.0,0.0,0.0,...,148,353,368,456,12,12,3717.232323,398.698990,1798.808081,475.965657
4,PRV51007,0,3,3,6333.333333,1068.0,4.0,4.0,6.0,0.0,...,18,41,42,49,12,12,3109.655172,423.517241,1497.241379,430.689655

In [22]:
df.PotentialFraud.value_counts()

0    4904
1     506
Name: PotentialFraud, dtype: int64

Here The data was Imbalanced.

### Checking Correlation Coefficent

- build a correlation matrix.
- identify Higly correlated variables.

In [23]:
corr_matrix=df.iloc[:,1:].corr()
corr_matrix

,PotentialFraud,IP_Claim_Count,IP_Benf_Count,Avg_IP_InscClaimAmtReimbursed,Avg_IP_DeductibleAmtPaid,Avg_IP_Number_of_Days_in_Hospital,Avg_IP_Number_of_Days_in_Hospital.1,Avg_IP_Number_of_Days_in_Hospital.2,Avg_IP_Number_of_Days_in_Hospital.3,OP_Claim_Count,...,IschemicHeart_Count,Osteoporosis_Count,RheumatoidArthritis_Count,Stroke_Count,Avg_PartA_Months,Avg_PartB_Months_Mode,Avg_IP_Reimbursement,Avg_IP_Deductible,Avg_OP_Reimbursement,Avg_OP_Deductible
PotentialFraud,1.000000,0.525393,0.522256,0.307556,0.319855,0.156278,0.157271,0.332043,0.203341,0.335803,...,0.369433,0.390565,0.388635,0.389683,0.009770,0.008369,0.127398,0.119897,-0.015204,-0.031547
IP_Claim_Count,0.525393,1.000000,0.997492,0.327985,0.398766,0.223728,0.224221,0.418265,0.228004,0.208758,...,0.325412,0.383660,0.379031,0.382209,0.009087,0.007868,0.165848,0.183794,-0.023449,-0.028603
IP_Benf_Count,0.522256,0.997492,1.000000,0.336416,0.409007,0.229987,0.230475,0.428677,0.231378,0.208244,...,0.328001,0.387186,0.382511,0.386015,0.009265,0.008031,0.170824,0.189412,-0.023422,-0.028680
Avg_IP_InscClaimAmtReimbursed,0.307556,0.327985,0.336416,1.000000,0.839577,0.672207,0.671091,0.827822,0.578765,0.022452,...,0.057874,0.079036,0.077457,0.078331,0.005905,0.010255,0.478656,0.411210,-0.007450,-0.026045
Avg_IP_DeductibleAmtPaid,0.319855,0.398766,0.409007,0.839577,1.000000,0.661765,0.662139,0.976286,0.566851,0.028770,...,0.074164,0.099966,0.097892,0.099275,-0.000936,0.003250,0.396898,0.433707,-0.029665,-0.042322
Avg_IP_Number_of_Days_in_Hospital,0.156278,0.223728,0.229987,0.672207,0.661765,1.000000,0.999488,0.664418,0.457804,0.004660,...,0.027244,0.041171,0.039813,0.040823,0.005033,0.002230,0.330939,0.321009,-0.029046,-0.028366
Avg_IP_Number_of_Days_in_Hospital.1,0.157271,0.224221,0.230475,0.671091,0.662139,0.999488,1.000000,0.665178,0.457536,0.004684,...,0.027227,0.041213,0.039873,0.040851,0.005025,0.002220,0.329952,0.321355,-0.028347,-0.028003
Avg_IP_Number_of_Days_in_Hospital.2,0.332043,0.418265,0.428677,0.827822,0.976286,0.664418,0.665178,1.000000,0.564605,0.035079,...,0.083536,0.110669,0.108475,0.109847,-0.002132,0.002353,0.395796,0.432281,-0.033373,-0.042564
Avg_IP_Number_of_Days_in_Hospital.3,0.203341,0.228004,0.231378,0.578765,0.566851,0.457804,0.457536,0.564605,1.000000,0.026307,...,0.049285,0.064725,0.063202,0.063827,-0.000450,0.011889,0.268412,0.269336,0.014888,0.008427
OP_Claim_Count,0.335803,0.208758,0.208244,0.022452,0.028770,0.004660,0.004684,0.035079,0.026307,1.000000,...,0.955746,0.933761,0.935031,0.931964,0.010603,0.009193,-0.088130,-0.093677,-0.044329,-0.047724
OP_Benf_Count,0.340550,0.276037,0.278841,0.039578,0.052258,0.014246,0.014232,0.060869,0.037751,0.945519,...,0.990307,0.992293,0.992839,0.992939,0.013319,0.011343,-0.093371,-0.098893,-0.029762,-0.033585
Avg_OP_InscClaimAmtReimbursed,0.046770,0.049353,0.047527,0.001402,-0.001592,-0.011352,-0.010703,0.000191,-0.016759,0.001186,...,0.004571,0.008397,0.008187,0.008214,0.002551,0.000497,0.006674,-0.002348,0.069217,0.031157
Avg_OP_DeductibleAmtPaid,0.041701,0.041827,0.040143,-0.002840,-0.005470,-0.013935,-0.013327,-0.004306,-0.022137,0.000996,...,0.004173,0.007072,0.006844,0.006885,-0.002991,0.005597,-0.014463,-0.015454,0.010879,-0.000074
Avg_OP_Number_of_Days_in_Hospital,-0.005206,-0.003967,-0.004631,-0.027280,-0.033019,-0.024043,-0.024054,-0.032110,-0.022597,-0.017896,...,-0.021316,-0.021386,-0.021361,-0.021433,0.001542,0.001321,-0.013031,-0.003642,0.076414,0.053224
Avg_OP_Number_of_Days_in_Hospital.1,-0.058295,-0.059130,-0.062674,-0.189112,-0.217772,-0.165073,-0.165012,-0.220298,-0.136844,-0.063512,...,-0.075240,-0.079118,-0.078077,-0.078390,0.006666,0.015780,-0.187670,-0.226209,0.038499,0.051594
Avg_OP_Number_of_Days_in_Hospital.2,0.042329,0.049632,0.048281,0.015028,0.017184,0.005287,0.005302,0.018245,-0.006204,-0.004832,...,-0.002224,0.001437,0.001191,0.001190,0.000414,0.000354,0.029087,0.027333,0.011210,-0.005009
Total_Beneficiaries,0.393531,0.391992,0.395842,0.081826,0.103420,0.043393,0.043442,0.114261,0.066001,0.928435,...,0.988919,0.999139,0.999005,0.999754,0.014011,0.011952,-0.064517,-0.067085,-0.030990,-0.035318
RenalDisease_Count,0.409965,0.443241,0.448558,0.103559,0.129415,0.057688,0.057776,0.141579,0.079412,0.877036,...,0.959671,0.982329,0.981588,0.983832,0.014684,0.012790,-0.045940,-0.047171,-0.012187,-0.016877
Alzheimer_Count,0.386035,0.367057,0.370378,0.072955,0.092288,0.036822,0.036856,0.102497,0.061304,0.939556,...,0.992788,0.998048,0.998252,0.998394,0.013675,0.011762,-0.070718,-0.074614,-0.033932,-0.038042
HeartFailure_Count,0.376435,0.346287,0.349185,0.063288,0.081232,0.030417,0.030392,0.090801,0.054007,0.948465,...,0.994742,0.995812,0.996242,0.995900,0.013383,0.011511,-0.076349,-0.080328,-0.037622,-0.041575
KidneyDisease_Count,0.375876,0.347629,0.350732,0.064599,0.082823,0.031614,0.031652,0.092603,0.054447,0.946493,...,0.994294,0.997408,0.997585,0.997596,0.013470,0.011438,-0.076888,-0.080668,-0.036706,-0.040729
Cancer_Count,0.391582,0.385222,0.388839,0.079234,0.100502,0.041575,0.041611,0.111179,0.064402,0.932253,...,0.990251,0.999093,0.999000,0.999567,0.013926,0.011829,-0.066558,-0.069302,-0.031997,-0.036428
Pulmonary_Count,0.381486,0.358068,0.361502,0.069923,0.088882,0.034699,0.034717,0.098858,0.058679,0.942205,...,0.993413,0.998273,0.998500,0.998603,0.013656,0.011617,-0.073311,-0.077001,-0.033762,-0.037946
Depression_Count,0.387190,0.370984,0.374276,0.074579,0.094274,0.038124,0.038179,0.104438,0.061208,0.939808,...,0.992216,0.998226,0.998276,0.998366,0.013774,0.011678,-0.069883,-0.073311,-0.033951,-0.037854
Diabetes_Count,0.375898,0.336251,0.338844,0.061251,0.077895,0.028899,0.028912,0.087117,0.052386,0.954256,...,0.994633,0.993510,0.993984,0.993254,0.013281,0.011126,-0.078171,-0.081929,-0.040403,-0.044096
IschemicHeart_Count,0.369433,0.325412,0.328001,0.057874,0.074164,0.027244,0.027227,0.083536,0.049285,0.955746,...,1.000000,0.990330,0.991240,0.990256,0.013149,0.011422,-0.080103,-0.083946,-0.040258,-0.044342
Osteoporosis_Count,0.390565,0.383660,0.387186,0.079036,0.099966,0.041171,0.041213,0.110669,0.064725,0.933761,...,0.990330,1.000000,0.998705,0.999103,0.013885,0.011760,-0.066699,-0.069683,-0.032514,-0.036642
RheumatoidArthritis_Count,0.388635,0.379031,0.382511,0.077457,0.097892,0.039813,0.039873,0.108475,0.063202,0.935031,...,0.991240,0.998705,1.000000,0.999064,0.013843,0.011817,-0.067603,-0.070851,-0.032744,-0.037174
Stroke_Count,0.389683,0.382209,0.386015,0.078331,0.099275,0.040823,0.040851,0.109847,0.063827,0.931964,...,0.990256,0.999103,0.999064,1.000000,0.013929,0.011837,-0.067324,-0.070163,-0.031716,-0.035887
Avg_PartA_Months,0.009770,0.009087,0.009265,0.005905,-0.000936,0.005033,0.005025,-0.002132,-0.000450,0.010603,...,0.013149,0.013885,0.013843,0.013929,1.000000,0.138254,0.003337,-0.000067,0.027455,0.002415
Avg_PartB_Months_Mode,0.008369,0.007868,0.008031,0.010255,0.003250,0.002230,0.002220,0.002353,0.011889,0.009193,...,0.011422,0.011760,0.011817,0.011837,0.138254,1.000000,0.010950,0.004001,0.004796,-0.003890
Avg_IP_Reimbursement,0.127398,0.165848,0.170824,0.478656,0.396898,0.330939,0.329952,0.395796,0.268412,-0.088130,...,-0.080103,-0.066699,-0.067603,-0.067324,0.003337,0.010950,1.000000,0.757567,0.091250,0.061456
Avg_IP_Deductible,0.119897,0.183794,0.189412,0.411210,0.433707,0.321009,0.321355,0.432281,0.269336,-0.093677,...,-0.083946,-0.069683,-0.070851,-0.070163,-0.000067,0.004001,0.757567,1.000000,0.082447,0.073925
Avg_OP_Reimbursement,-0.015204,-0.023449,-0.023422,-0.007450,-0.029665,-0.029046,-0.028347,-0.033373,0.014888,-0.044329,...,-0.040258,-0.032514,-0.032744,-0.031716,0.027455,0.004796,0.091250,0.082447,1.000000,0.838188
Avg_OP_Deductible,-0.031547,-0.028603,-0.028680,-0.026045,-0.042322,-0.028366,-0.028003,-0.042564,0.008427,-0.047724,...,-0.044342,-0.036642,-0.037174,-0.035887,0.002415,-0.003890,0.061456,0.073925,0.838188,1.000000

In [24]:
check=corr_matrix['IP_Claim_Count'].apply(lambda x: 0.8>= x<1)
check

PotentialFraud                          True
IP_Claim_Count                         False
IP_Benf_Count                          False
Avg_IP_InscClaimAmtReimbursed           True
Avg_IP_DeductibleAmtPaid                True
Avg_IP_Number_of_Days_in_Hospital       True
Avg_IP_Number_of_Days_in_Hospital.1     True
Avg_IP_Number_of_Days_in_Hospital.2     True
Avg_IP_Number_of_Days_in_Hospital.3     True
OP_Claim_Count                          True
OP_Benf_Count                           True
Avg_OP_InscClaimAmtReimbursed           True
Avg_OP_DeductibleAmtPaid                True
Avg_OP_Number_of_Days_in_Hospital       True
Avg_OP_Number_of_Days_in_Hospital.1     True
Avg_OP_Number_of_Days_in_Hospital.2     True
Total_Beneficiaries                     True
RenalDisease_Count                      True
Alzheimer_Count                         True
HeartFailure_Count                      True
KidneyDisease_Count                     True
Cancer_Count                            True
Pulmonary_Count                         True
Depression_Count                        True
Diabetes_Count                          True
IschemicHeart_Count                     True
Osteoporosis_Count                      True
RheumatoidArthritis_Count               True
Stroke_Count                            True
Avg_PartA_Months                        True
Avg_PartB_Months_Mode                   True
Avg_IP_Reimbursement                    True
Avg_IP_Deductible                       True
Avg_OP_Reimbursement                    True
Avg_OP_Deductible                       True
Name: IP_Claim_Count, dtype: bool

In [25]:
cols = list(corr_matrix.columns)

check = corr_matrix.apply(lambda row :  [row[c] if 0.8<=abs(row[c])<1 else None for c in cols ])
check

,PotentialFraud,IP_Claim_Count,IP_Benf_Count,Avg_IP_InscClaimAmtReimbursed,Avg_IP_DeductibleAmtPaid,Avg_IP_Number_of_Days_in_Hospital,Avg_IP_Number_of_Days_in_Hospital.1,Avg_IP_Number_of_Days_in_Hospital.2,Avg_IP_Number_of_Days_in_Hospital.3,OP_Claim_Count,...,IschemicHeart_Count,Osteoporosis_Count,RheumatoidArthritis_Count,Stroke_Count,Avg_PartA_Months,Avg_PartB_Months_Mode,Avg_IP_Reimbursement,Avg_IP_Deductible,Avg_OP_Reimbursement,Avg_OP_Deductible
PotentialFraud,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
IP_Claim_Count,None,NaN,0.997492,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
IP_Benf_Count,None,0.997492,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_IP_InscClaimAmtReimbursed,None,NaN,NaN,NaN,0.839577,NaN,NaN,0.827822,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_IP_DeductibleAmtPaid,None,NaN,NaN,0.839577,NaN,NaN,NaN,0.976286,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_IP_Number_of_Days_in_Hospital,None,NaN,NaN,NaN,NaN,NaN,0.999488,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_IP_Number_of_Days_in_Hospital.1,None,NaN,NaN,NaN,NaN,0.999488,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_IP_Number_of_Days_in_Hospital.2,None,NaN,NaN,0.827822,0.976286,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_IP_Number_of_Days_in_Hospital.3,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
OP_Claim_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,0.955746,0.933761,0.935031,0.931964,None,None,None,None,NaN,NaN
OP_Benf_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.945519,...,0.990307,0.992293,0.992839,0.992939,None,None,None,None,NaN,NaN
Avg_OP_InscClaimAmtReimbursed,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_OP_DeductibleAmtPaid,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_OP_Number_of_Days_in_Hospital,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_OP_Number_of_Days_in_Hospital.1,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_OP_Number_of_Days_in_Hospital.2,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Total_Beneficiaries,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.928435,...,0.988919,0.999139,0.999005,0.999754,None,None,None,None,NaN,NaN
RenalDisease_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.877036,...,0.959671,0.982329,0.981588,0.983832,None,None,None,None,NaN,NaN
Alzheimer_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.939556,...,0.992788,0.998048,0.998252,0.998394,None,None,None,None,NaN,NaN
HeartFailure_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.948465,...,0.994742,0.995812,0.996242,0.995900,None,None,None,None,NaN,NaN
KidneyDisease_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.946493,...,0.994294,0.997408,0.997585,0.997596,None,None,None,None,NaN,NaN
Cancer_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.932253,...,0.990251,0.999093,0.999000,0.999567,None,None,None,None,NaN,NaN
Pulmonary_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.942205,...,0.993413,0.998273,0.998500,0.998603,None,None,None,None,NaN,NaN
Depression_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.939808,...,0.992216,0.998226,0.998276,0.998366,None,None,None,None,NaN,NaN
Diabetes_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.954256,...,0.994633,0.993510,0.993984,0.993254,None,None,None,None,NaN,NaN
IschemicHeart_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.955746,...,NaN,0.990330,0.991240,0.990256,None,None,None,None,NaN,NaN
Osteoporosis_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.933761,...,0.990330,NaN,0.998705,0.999103,None,None,None,None,NaN,NaN
RheumatoidArthritis_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.935031,...,0.991240,0.998705,NaN,0.999064,None,None,None,None,NaN,NaN
Stroke_Count,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0.931964,...,0.990256,0.999103,0.999064,NaN,None,None,None,None,NaN,NaN
Avg_PartA_Months,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_PartB_Months_Mode,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_IP_Reimbursement,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_IP_Deductible,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN
Avg_OP_Reimbursement,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,NaN,0.838188
Avg_OP_Deductible,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,0.838188,NaN

In [26]:
corr_matrix.columns

Index(['PotentialFraud', 'IP_Claim_Count', 'IP_Benf_Count',
       'Avg_IP_InscClaimAmtReimbursed', 'Avg_IP_DeductibleAmtPaid',
       'Avg_IP_Number_of_Days_in_Hospital',
       'Avg_IP_Number_of_Days_in_Hospital.1',
       'Avg_IP_Number_of_Days_in_Hospital.2',
       'Avg_IP_Number_of_Days_in_Hospital.3', 'OP_Claim_Count',
       'OP_Benf_Count', 'Avg_OP_InscClaimAmtReimbursed',
       'Avg_OP_DeductibleAmtPaid', 'Avg_OP_Number_of_Days_in_Hospital',
       'Avg_OP_Number_of_Days_in_Hospital.1',
       'Avg_OP_Number_of_Days_in_Hospital.2', 'Total_Beneficiaries',
       'RenalDisease_Count', 'Alzheimer_Count', 'HeartFailure_Count',
       'KidneyDisease_Count', 'Cancer_Count', 'Pulmonary_Count',
       'Depression_Count', 'Diabetes_Count', 'IschemicHeart_Count',
       'Osteoporosis_Count', 'RheumatoidArthritis_Count', 'Stroke_Count',
       'Avg_PartA_Months', 'Avg_PartB_Months_Mode', 'Avg_IP_Reimbursement',
       'Avg_IP_Deductible', 'Avg_OP_Reimbursement', 'Avg_OP_Deductible'],
      dtype='object')

In [50]:
def correlated_vars(df):
    df1=df.copy()
    cols=list(df1.columns)    
    final_data=[]
    for index,row in df1.iterrows():
        cor_dict={}
        for c in cols:
            if 0.8<=abs(row[c])<1:
                k={c:row[c]}
                l=list(cor_dict.update(k))
            final_data.append(l)
    return final_data

correlated_vars(df=corr_matrix)

UnboundLocalError: local variable 'l' referenced before assignment

1.0
0.5253931054046992
0.5222557305392744
0.3075555268937365
0.31985536783085267
0.1562775929876254
0.15727106255761023
0.3320434678504162
0.20334057009913656
0.33580338914242047
0.3405502378836281
0.04676980519640057
0.041700915208835135
-0.005206264902285629
-0.05829491185949908
0.04232933850062358
0.3935310970429305
0.40996544241628047
0.38603451003479167
0.3764347485861789
0.3758755406956482
0.39158247973938504
0.381486495866275
0.38718987210256745
0.37589823294895736
0.36943256838382776
0.3905651831096477
0.38863453053950714
0.38968258905975695
0.009769833910861395
0.008369433632351186
0.1273981778197977
0.11989720065379376
-0.015203758422288082
-0.03154701516960908
0.5253931054046992
1.0
0.9974923038377357
0.32798513390016565
0.39876596457977936
0.22372848425358638
0.22422141546340923
0.41826532649444215
0.22800437445050895
0.20875848901088
0.2760373311623612
0.0493527092028107
0.0418273716126947
-0.003966718263774776
-0.059130301868437984
0.04963246650691962
0.39199230512963545
0.4432414108341603
0.36705680443577937
0.34628660327613886
0.3476290906939807
0.38522174828593414
0.3580679197090131
0.3709837387776325
0.33625148427955404
0.3254124170152738
0.38365973801576775
0.37903065720902035
0.38220926831639956
0.009086916943086495
0.007867594628220217
0.16584842930524607
0.18379424134996186
-0.023449018432217802
-0.028602953844217533
0.5222557305392744
0.9974923038377357
1.0
0.33641617849269273
0.4090065751665957
0.2299867710853269
0.2304752362945132
0.42867678728500785
0.2313781863924282
0.20824419880097716
0.2788411728374962
0.04752711143748726
0.04014276742782832
-0.004630995261664321
-0.06267365371174946
0.04828141223518059
0.3958421049659739
0.4485584718948225
0.3703775009965683
0.3491846151014693
0.3507322402109942
0.38883939254252703
0.3615017357537099
0.37427593658478236
0.3388439035045376
0.3280012582345503
0.38718633346584397
0.3825108888210299
0.38601500161820573
0.009265158034604263
0.008031416959707076
0.17082418351912254
0.18941215243540122
-0.023421658805578786
-0.028679654679413743
0.3075555268937365
0.32798513390016565
0.33641617849269273
1.0
0.8395768433340393
0.672206640525926
0.6710909274187848
0.8278217641888971
0.5787653732577676
0.02245154559929816
0.039577564465646274
0.001402138785183644
-0.002840408833608757
-0.027279799291442794
-0.1891119808758269
0.015027986455738785
0.08182571838723723
0.10355884169558688
0.07295482516253486
0.063287932358188
0.06459866950279014
0.07923417874248395
0.06992277327480326
0.07457896152563007
0.06125051747190051
0.05787350527707222
0.07903610524605686
0.07745740523019656
0.07833057819823848
0.005905442920807243
0.01025458601224169
0.4786563969746057
0.4112096198698498
-0.007450127053251772
-0.02604529719191605
0.31985536783085267
0.39876596457977936
0.4090065751665957
0.8395768433340393
1.0
0.6617653697427719
0.6621386074208278
0.9762855605662335
0.5668507761991086
0.0287702430629031
0.052257730538568206
-0.0015918117196908155
-0.005469766415320162
-0.03301929686219607
-0.21777235597153352
0.01718396085658905
0.10341997413356978
0.12941470511538244
0.09228843994686589
0.08123223365165831
0.08282281489106956
0.10050164085887443
0.0888817568271753
0.09427377807226943
0.07789500234847414
0.07416440915951056
0.09996598582631379
0.09789221208177926
0.09927511423605158
-0.0009358389925516797
0.0032503887306353117
0.39689785543902767
0.4337073325563174
-0.02966494977859601
-0.04232201663603919
0.1562775929876254
0.22372848425358638
0.2299867710853269
0.672206640525926
0.6617653697427719
1.0
0.9994878014814029
0.6644182064210509
0.457803646752815
0.004660370340272844
0.014245662106353366
-0.011351664848757962
-0.01393474294347239
-0.024042733014424916
-0.165073199899233
0.005286982498260061
0.0433933129656944
0.057687746688131904
0.03682178264014378
0.03041703355646153
0.03161438072916237
0.04157470890762564
0.03469900002428297
0.03812441717401352
0.028899219277950697
0.027244275157724665
0.0411705578679873
0.03981251061104536
0.040822647751988066
0.005032853199909538
0.0022296197611691515
0.33093893270627817
0.32100853708585275
-0.029046447805305197
-0.028366424463939624
0.15727106255761023
0.22422141546340923
0.2304752362945132
0.6710909274187848
0.6621386074208278
0.9994878014814029
1.0
0.6651784417859018
0.45753594031497613
0.004683994840740647
0.014232105587540721
-0.010703057610514268
-0.013326863663264406
-0.024053833302167538
-0.1650118017098489
0.005302121449347755
0.043442285995853404
0.05777616651855135
0.036855648300463624
0.030392376636368887
0.031652400636763826
0.0416110253270528
0.03471728929388573
0.0381789798794045
0.028911570660813516
0.02722712038523745
0.041213389952209786
0.03987291670014837
0.04085130420392022
0.005025017684850327
0.0022196932861491265
0.3299519843144686
0.32135532885105106
-0.02834664059560243
-0.02800322477278036
0.3320434678504162
0.41826532649444215
0.42867678728500785
0.8278217641888971
0.9762855605662335
0.6644182064210509
0.6651784417859018
1.0
0.5646050226802585
0.03507898234688476
0.06086875709827417
0.0001914546809848672
-0.004305924130457865
-0.0321104633032823
-0.22029767602012998
0.01824455269622964
0.11426086551948182
0.14157934489896692
0.10249660498603406
0.09080057958902854
0.09260288576064579
0.11117904475778743
0.09885830044959143
0.10443799524102233
0.08711679684729194
0.08353562089482403
0.11066917003907428
0.10847485621654776
0.10984738248534595
-0.002131649241430613
0.0023531158794995784
0.39579615210662783
0.4322811155544053
-0.033373200575987985
-0.042564109683632605
0.20334057009913656
0.22800437445050895
0.2313781863924282
0.5787653732577676
0.5668507761991086
0.457803646752815
0.45753594031497613
0.5646050226802585
1.0
0.026307236295580697
0.03775124320045954
-0.016759281226029335
-0.02213686559346494
-0.022596691922524732
-0.1368438675476273
-0.006204472984892389
0.06600112099017154
0.07941154703874181
0.06130445792688519
0.05400720811566833
0.05444735778226033
0.06440237538416935
0.05867884286057369
0.061207769214447906
0.052386278493272764
0.049285228506437365
0.0647245664025685
0.06320241583513603
0.06382654905778981
-0.00045026498586798525
0.011889386103630937
0.26841228102472997
0.26933588167163075
0.014888064307604287
0.008427422362900772
0.33580338914242047
0.20875848901088
0.20824419880097716
0.02245154559929816
0.0287702430629031
0.004660370340272844
0.004683994840740647
0.03507898234688476
0.026307236295580697
1.0
0.9455186100476624
0.0011859327982775062
0.0009963702279619099
-0.017896238899538713
-0.06351194970548518
-0.004831711211522518
0.9284349947920647
0.8770360129529308
0.9395561588033772
0.9484651037669627
0.946492803992573
0.9322529881610545
0.9422051010669737
0.9398080478984608
0.9542563571480023
0.9557455706885131
0.9337612043894676
0.9350313968698152
0.9319637534282831
0.010602599275877046
0.009192756233298727
-0.08812965518175622
-0.09367737052683979
-0.04432938721278903
-0.04772405164120884
0.3405502378836281
0.2760373311623612
0.2788411728374962
0.039577564465646274
0.052257730538568206
0.014245662106353366
0.014232105587540721
0.06086875709827417
0.03775124320045954
0.9455186100476624
1.0
0.0015970530656790774
0.0011955399656620085
-0.02196683042658127
-0.07369856970531588
-0.005954346336097756
0.9917895657032916
0.9685954727723581
0.9936104967565254
0.9934593938693013
0.9951960734539625
0.9924839413213725
0.9948871688062608
0.9931457004312849
0.9921687106489374
0.9903074864865926
0.9922934779691357
0.9928391454104526
0.9929389200219852
0.01331924892700102
0.01134342904932466
-0.09337057883941915
-0.09889255872382907
-0.029762001325435973
-0.03358473160492668
0.04676980519640057
0.0493527092028107
0.04752711143748726
0.001402138785183644
-0.0015918117196908155
-0.011351664848757962
-0.010703057610514268
0.0001914546809848672
-0.016759281226029335
0.0011859327982775062
0.0015970530656790774
1.0
0.9132526783790547
0.22773358376303404
0.1632266185371471
0.9845272453277947
0.008353144599223915
0.009997510337150123
0.007043625967658402
0.0061309539963953965
0.006508862474918708
0.0076968500624339875
0.006918239395662027
0.007539932708960486
0.006042336674046176
0.0045709827984891345
0.008396885824300197
0.008186797309871279
0.008214470160452078
0.0025510132849420435
0.0004968331667653958
0.006673688687322369
-0.0023476182965854048
0.06921673672512532
0.031156675015387
0.041700915208835135
0.0418273716126947
0.04014276742782832
-0.002840408833608757
-0.005469766415320162
-0.01393474294347239
-0.013326863663264406
-0.004305924130457865
-0.02213686559346494
0.0009963702279619099
0.0011955399656620085
0.9132526783790547
1.0
0.19923637312906733
0.14661710148045393
0.9178101454650512
0.006900944477005049
0.0069312987269677575
0.005913546991142999
0.0054557554570949926
0.005669098396237015
0.0063621393228132355
0.005883521250064303
0.006265547874810593
0.005196218301842911
0.00417307902862163
0.007071906794718454
0.006843916904582311
0.006885458410055871
-0.0029910527800334915
0.005596571800896157
-0.014463199070134514
-0.015454277366762132
0.010879388625446785
-7.41162602524535e-05
-0.005206264902285629
-0.003966718263774776
-0.004630995261664321
-0.027279799291442794
-0.03301929686219607
-0.024042733014424916
-0.024053833302167538
-0.0321104633032823
-0.022596691922524732
-0.017896238899538713
-0.02196683042658127
0.22773358376303404
0.19923637312906733
1.0
0.10534530313732789
0.21973148140285068
-0.021566245114070324
-0.02191869881891873
-0.02150980473052752
-0.02120785229669381
-0.02122899742023487
-0.021527680430498696
-0.02149351377608072
-0.021389690767011426
-0.020977074568936348
-0.02131565769766207
-0.02138624457097986
-0.021360641712416476
-0.021433006147122194
0.001542341843675402
0.0013212637816382856
-0.01303121291947966
-0.0036416948203511707
0.07641418580377991
0.053223651404918935
-0.05829491185949908
-0.059130301868437984
-0.06267365371174946
-0.1891119808758269
-0.21777235597153352
-0.165073199899233
-0.1650118017098489
-0.22029767602012998
-0.1368438675476273
-0.06351194970548518
-0.07369856970531588
0.1632266185371471
0.14661710148045393
0.10534530313732789
1.0
0.14284110110507944
-0.07907638302733186
-0.08152279829006168
-0.07774796663562954
-0.07655983706666686
-0.07664350253390795
-0.07867246907372817
-0.07763223028721086
-0.07815285862427412
-0.0759335273030856
-0.07523985426737018
-0.07911768134761529
-0.07807692192961259
-0.07838995263006236
0.006665750604054056
0.015779874122650552
-0.18767038431465827
-0.226209252005117
0.03849937173106735
0.051593519492965194
0.04232933850062358
0.04963246650691962
0.04828141223518059
0.015027986455738785
0.01718396085658905
0.005286982498260061
0.005302121449347755
0.01824455269622964
-0.006204472984892389
-0.004831711211522518
-0.005954346336097756
0.9845272453277947
0.9178101454650512
0.21973148140285068
0.14284110110507944
1.0
0.0013190216782425848
0.002125369887835764
0.00010359427062957715
-0.0006545208586377756
-0.0003148347464676318
0.0007201233722274998
-3.3036908010320436e-05
0.00059140596457765
-0.0006950556120507881
-0.002223534961113657
0.0014365672244185889
0.0011909012577899878
0.0011901372067622308
0.0004135506067078166
0.0003542725892824359
0.02908719348074978
0.027332762331685655
0.011210088586645274
-0.005009120268744843
0.3935310970429305
0.39199230512963545
0.3958421049659739
0.08182571838723723
0.10341997413356978
0.0433933129656944
0.043442285995853404
0.11426086551948182
0.06600112099017154
0.9284349947920647
0.9917895657032916
0.008353144599223915
0.006900944477005049
-0.021566245114070324
-0.07907638302733186
0.0013190216782425848
1.0
0.985615309263807
0.9980224284428012
0.9949763821473856
0.9968952260126741
0.999638348194514
0.9981502714817647
0.9981044015018702
0.9921916109736685
0.9889189649323733
0.9991387625745617
0.999004892019751
0.9997535203814653
0.014011137298912726
0.011952469421606535
-0.06451707178688845
-0.06708477304777524
-0.030990081622779747
-0.035317923426854345
0.40996544241628047
0.4432414108341603
0.4485584718948225
0.10355884169558688
0.12941470511538244
0.057687746688131904
0.05777616651855135
0.14157934489896692
0.07941154703874181
0.8770360129529308
0.9685954727723581
0.009997510337150123
0.0069312987269677575
-0.02191869881891873
-0.08152279829006168
0.002125369887835764
0.985615309263807
1.0
0.9783720735531553
0.9699170539515981
0.9726701168491155
0.9836197624691287
0.9775612978936925
0.9782912341420573
0.9650806207160866
0.9596705597787788
0.9823294098961256
0.9815882709584742
0.9838322619280725
0.014684307115535459
0.012790257879670804
-0.04594036308693334
-0.047170932462410955
-0.012187288649775939
-0.016877267006666644
0.38603451003479167
0.36705680443577937
0.3703775009965683
0.07295482516253486
0.09228843994686589
0.03682178264014378
0.036855648300463624
0.10249660498603406
0.06130445792688519
0.9395561588033772
0.9936104967565254
0.007043625967658402
0.005913546991142999
-0.02150980473052752
-0.07774796663562954
0.00010359427062957715
0.9980224284428012
0.9783720735531553
1.0
0.9967939544708054
0.9979202761652513
0.998293858436116
0.9985158623974556
0.9981495094275179
0.9950826690645911
0.9927878322726403
0.9980481943955993
0.9982522411866868
0.9983941728117038
0.013675177139237165
0.011762108026186165
-0.07071778461339212
-0.07461395271298361
-0.033932350541810145
-0.038041806275277416
0.3764347485861789
0.34628660327613886
0.3491846151014693
0.063287932358188
0.08123223365165831
0.03041703355646153
0.030392376636368887
0.09080057958902854
0.05400720811566833
0.9484651037669627
0.9934593938693013
0.0061309539963953965
0.0054557554570949926
-0.02120785229669381
-0.07655983706666686
-0.0006545208586377756
0.9949763821473856
0.9699170539515981
0.9967939544708054
1.0
0.9978000637920528
0.9957720140819063
0.9974987531223399
0.996863373706459
0.9962021991248279
0.9947416714700853
0.9958121497882965
0.9962416653970182
0.9959002965132991
0.013383467398756054
0.011510724446972969
-0.07634893541679956
-0.08032750037280557
-0.037622258090344717
-0.04157549654545007
0.3758755406956482
0.3476290906939807
0.3507322402109942
0.06459866950279014
0.08282281489106956
0.03161438072916237
0.031652400636763826
0.09260288576064579
0.05444735778226033
0.946492803992573
0.9951960734539625
0.006508862474918708
0.005669098396237015
-0.02122899742023487
-0.07664350253390795
-0.0003148347464676318
0.9968952260126741
0.9726701168491155
0.9979202761652513
0.9978000637920528
1.0
0.997463864082495
0.9986957183253222
0.9978830533934309
0.9964259848023814
0.9942939039019805
0.9974083583716208
0.9975850223986545
0.9975961663449475
0.01347033969901659
0.011438394713191554
-0.076888045907758
-0.08066844668786573
-0.036705904327283316
-0.04072892578887886
0.39158247973938504
0.38522174828593414
0.38883939254252703
0.07923417874248395
0.10050164085887443
0.04157470890762564
0.0416110253270528
0.11117904475778743
0.06440237538416935
0.9322529881610545
0.9924839413213725
0.0076968500624339875
0.0063621393228132355
-0.021527680430498696
-0.07867246907372817
0.0007201233722274998
0.999638348194514
0.9836197624691287
0.998293858436116
0.9957720140819063
0.997463864082495
1.0
0.9984851762057549
0.9983102382424879
0.993279988317333
0.9902506506818636
0.9990930768969172
0.999000104419948
0.9995670675121924
0.013926289003505659
0.011829289382593353
-0.06655768433887777
-0.06930170139893475
-0.03199729322408677
-0.036427968856597256
0.381486495866275
0.3580679197090131
0.3615017357537099
0.06992277327480326
0.0888817568271753
0.03469900002428297
0.03471728929388573
0.09885830044959143
0.05867884286057369
0.9422051010669737
0.9948871688062608
0.006918239395662027
0.005883521250064303
-0.02149351377608072
-0.07763223028721086
-3.3036908010320436e-05
0.9981502714817647
0.9775612978936925
0.9985158623974556
0.9974987531223399
0.9986957183253222
0.9984851762057549
1.0
0.9983951952232802
0.9954748673811343
0.993413449937045
0.998273244901606
0.9984999279922154
0.9986028489396901
0.013656455037871376
0.011616912125323777
-0.07331093028587442
-0.07700064215156607
-0.03376231421292
-0.03794617978240593
0.38718987210256745
0.3709837387776325
0.37427593658478236
0.07457896152563007
0.09427377807226943
0.03812441717401352
0.0381789798794045
0.10443799524102233
0.061207769214447906
0.9398080478984608
0.9931457004312849
0.007539932708960486
0.006265547874810593
-0.021389690767011426
-0.07815285862427412
0.00059140596457765
0.9981044015018702
0.9782912341420573
0.9981495094275179
0.996863373706459
0.9978830533934309
0.9983102382424879
0.9983951952232802
1.0
0.9950856295036574
0.9922159547128863
0.9982262416369355
0.9982763562758681
0.9983657469402424
0.013774356338981697
0.011677939290536078
-0.06988315915554807
-0.07331057426602984
-0.033951357816719
-0.03785351857744557
0.37589823294895736
0.33625148427955404
0.3388439035045376
0.06125051747190051
0.07789500234847414
0.028899219277950697
0.028911570660813516
0.08711679684729194
0.052386278493272764
0.9542563571480023
0.9921687106489374
0.006042336674046176
0.005196218301842911
-0.020977074568936348
-0.0759335273030856
-0.0006950556120507881
0.9921916109736685
0.9650806207160866
0.9950826690645911
0.9962021991248279
0.9964259848023814
0.993279988317333
0.9954748673811343
0.9950856295036574
1.0
0.9946334249230411
0.9935097343061438
0.9939842656887623
0.9932537306610595
0.013280890277712336
0.011126158174852156
-0.07817070360575983
-0.08192881495174635
-0.04040268993329246
-0.04409630924232225
0.36943256838382776
0.3254124170152738
0.3280012582345503
0.05787350527707222
0.07416440915951056
0.027244275157724665
0.02722712038523745
0.08353562089482403
0.049285228506437365
0.9557455706885131
0.9903074864865926
0.0045709827984891345
0.00417307902862163
-0.02131565769766207
-0.07523985426737018
-0.002223534961113657
0.9889189649323733
0.9596705597787788
0.9927878322726403
0.9947416714700853
0.9942939039019805
0.9902506506818636
0.993413449937045
0.9922159547128863
0.9946334249230411
1.0
0.9903303761920129
0.9912403751356035
0.9902559601422998
0.013149358800601346
0.011421685117290815
-0.08010275099746651
-0.08394556044375871
-0.040257542462537405
-0.04434244570867586
0.3905651831096477
0.38365973801576775
0.38718633346584397
0.07903610524605686
0.09996598582631379
0.0411705578679873
0.041213389952209786
0.11066917003907428
0.0647245664025685
0.9337612043894676
0.9922934779691357
0.008396885824300197
0.007071906794718454
-0.02138624457097986
-0.07911768134761529
0.0014365672244185889
0.9991387625745617
0.9823294098961256
0.9980481943955993
0.9958121497882965
0.9974083583716208
0.9990930768969172
0.998273244901606
0.9982262416369355
0.9935097343061438
0.9903303761920129
1.0
0.9987049378674882
0.9991026367519843
0.013884618179698938
0.011760094433916596
-0.0666987289516911
-0.06968314352015134
-0.03251360178485279
-0.036642376774562016
0.38863453053950714
0.37903065720902035
0.3825108888210299
0.07745740523019656
0.09789221208177926
0.03981251061104536
0.03987291670014837
0.10847485621654776
0.06320241583513603
0.9350313968698152
0.9928391454104526
0.008186797309871279
0.006843916904582311
-0.021360641712416476
-0.07807692192961259
0.0011909012577899878
0.999004892019751
0.9815882709584742
0.9982522411866868
0.9962416653970182
0.9975850223986545
0.999000104419948
0.9984999279922154
0.9982763562758681
0.9939842656887623
0.9912403751356035
0.9987049378674882
1.0
0.999064151599216
0.01384308205351808
0.011817132523664314
-0.06760346050173005
-0.07085095630418264
-0.032744251049890274
-0.03717399723104722
0.38968258905975695
0.38220926831639956
0.38601500161820573
0.07833057819823848
0.09927511423605158
0.040822647751988066
0.04085130420392022
0.10984738248534595
0.06382654905778981
0.9319637534282831
0.9929389200219852
0.008214470160452078
0.006885458410055871
-0.021433006147122194
-0.07838995263006236
0.0011901372067622308
0.9997535203814653
0.9838322619280725
0.9983941728117038
0.9959002965132991
0.9975961663449475
0.9995670675121924
0.9986028489396901
0.9983657469402424
0.9932537306610595
0.9902559601422998
0.9991026367519843
0.999064151599216
1.0
0.013928826480171259
0.011836788994059138
-0.06732417365906404
-0.07016263586576048
-0.0317164066539141
-0.03588652041479708