In [1]:
import pickle
import pandas as pd
import numpy as np

### Load saved model in the training phase

In [2]:
with open("../Models/lgbm_desired.pkl","rb") as f:
    model=pickle.load(f)

In [3]:
data=pd.read_csv("../Model_Input_Data/prediction_input_data.csv")
data.head()

,Provider,IP_Claim_Count,IP_Benf_Count,Avg_IP_InscClaimAmtReimbursed,Avg_IP_DeductibleAmtPaid,Avg_IP_Number_of_Days_in_Hospital,Avg_IP_Claim_Days,Avg_IP_Unique_Disease_Count,Avg_IP_Unique_Treatment_Count,OP_Claim_Count,...,IschemicHeart_Count,Osteoporosis_Count,RheumatoidArthritis_Count,Stroke_Count,Avg_PartA_Months,Avg_PartB_Months_Mode,Avg_IP_Reimbursement,Avg_IP_Deductible,Avg_OP_Reimbursement,Avg_OP_Deductible
0,PRV51002,0,0,0.000000,0.0,0.0,0.0,0.0,0.0,205,...,46,120,124,156,12,12,4719.467456,519.692308,2064.852071,594.497041
1,PRV51006,0,0,0.000000,0.0,0.0,0.0,0.0,0.0,102,...,18,60,66,73,12,12,3670.246914,458.962963,2439.259259,671.358025
2,PRV51009,2,2,7500.000000,1068.0,3.0,3.0,5.0,1.0,37,...,8,19,26,27,12,12,3905.333333,320.400000,2985.333333,729.333333
3,PRV51010,6,5,9333.333333,1068.0,0.0,0.0,5.0,0.0,32,...,6,17,19,21,12,12,4168.000000,384.480000,2002.000000,632.800000
4,PRV51018,0,0,0.000000,0.0,0.0,0.0,0.0,0.0,190,...,45,100,110,137,12,12,3911.438356,409.643836,2330.821918,689.589041

In [5]:
x_var=data.reindex(columns=model.feature_names_in_,fill_value=0)

In [8]:
predictions=model.predict(x_var)
prob=model.predict_proba(x_var)
prob_fraud=[row[1] for row in prob]
provider=data['Provider']
results=pd.DataFrame({'Provider':provider,'predictions':predictions,'Fraud_Probability':prob_fraud})
results['Fraud_Probability']=results['Fraud_Probability'].apply(lambda x:round(x,3))
results

      Provider  predictions  Fraud_Probability
0     PRV51002            0              0.086
1     PRV51006            0              0.048
2     PRV51009            0              0.081
3     PRV51010            0              0.234
4     PRV51018            0              0.075
...        ...          ...                ...
1348  PRV57713            0              0.017
1349  PRV57726            0              0.020
1350  PRV57745            0              0.028
1351  PRV57749            0              0.102
1352  PRV57750            0              0.083

[1353 rows x 3 columns]

### Top 100 Suspicious records

In [13]:
results[results['predictions']==1].sort_values(by='Fraud_Probability',ascending=False).head(100)

      Provider  predictions  Fraud_Probability
266   PRV52338            1              0.983
418   PRV53105            1              0.982
745   PRV54751            1              0.982
750   PRV54766            1              0.981
86    PRV51407            1              0.980
...        ...          ...                ...
805   PRV54989            1              0.828
968   PRV55838            1              0.827
1274  PRV57337            1              0.824
800   PRV54974            1              0.821
36    PRV51163            1              0.821

[100 rows x 3 columns]